Secondary mode
TheStonedTurtle/banked-experience pull request #121
Opened 2023-09-12 18:48 UTC by harbingerofme

Fixes #111 
Changes the config option for show secondaries to also have a show missing secondaries only mode.
![a](https://cdn.discordapp.com/attachments/132978900841136139/1151211171093942292/image.png)
![b}(https://cdn.discordapp.com/attachments/132978900841136139/1151211171093942292/image.png)
![c](https://cdn.discordapp.com/attachments/132978900841136139/1151211171660189786/image.png)
The old display is still supported (and probably preferred for most users)
![d](https://cdn.discordapp.com/attachments/132978900841136139/1151211171949580298/image.png)

Currently still in draft as I need to fix the secondary grid display not redrawing/reloading if the config option is changed.

Thank you @DrJam for supplying the images.

2023-09-12 19:40 UTC, harbingerofme commented
Should be ready, just haven't had time to compile and test yet.

2023-09-20 19:14 UTC, harbingerofme commented
Fixed changing what secondaries are shown not refreshing the panel.

2023-11-04 23:31 UTC, TheStonedTurtle requested changes
Sorry it took me so long to review, lifes been busy

2023-11-04 23:31 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/SecondaryGrid.java
> +			if (mode == SecondaryMode.ALL) {
I'd prefer a guard clause here such as:
```java
if (mode == SecondaryMode.MISSING && result >= 0) {
    continue;
}
```

Then get rid of all of this nested checking else if stuff and do:
```java
int displayedNumber = mode == SecondaryMode.MISSING ? Math.abs(result) : qty;
calc.getItemManager().getImage(itemID, displayedNumber, displayedNumber> 0).addTo(label);
```

2023-11-04 23:31 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/BankedExperienceConfig.java
> +			position = 2
Match previous indentation levels, and lets update the displayed text to be a little more informative

```java
name="Secondary display mode",
description= "<html>Controls how the required secondaries grid will be displayed."
	+ "<br/><br/><strong>None</strong>: Grid is not displayed at all<br/>"
	+ "<strong>All</strong>: Shows all items required & how many are missing or extra<br/>"
	+ "<strong>Missing</strong>: Like <strong>All</strong> but just the items you are missing"
	+ "</html>",
```

You should now see something like this on hover: 
![image](https://github.com/TheStonedTurtle/banked-experience/assets/29030969/f5f62882-e5e1-44db-9c1d-5471dcf5da39)

2025-01-17 19:12 UTC, harbingerofme commented
I'm afraid I cannot make any of the requested changes. Medical issues have left me unable to code in most capacities.

2025-01-17 19:12 UTC, closed without merging