Bulk Ignore & Include Items
TheStonedTurtle/banked-experience pull request #91
Opened 2022-09-18 19:19 UTC by zmanowar

- Adds two new buttons `Include All` and `Ignore All`
  - Wraps them in a panel to display them as a row
  - Bulkifies ignoring / including by iterating over the grid items.
- Adds config to enable / disable buttons

![image](https://user-images.githubusercontent.com/39996391/190924655-5a980f43-09af-4b18-95fe-7afe059610c7.png)

2022-09-18 19:22 UTC, zmanowar commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +	public void setIgnore(Boolean ignored) {
There's a refactoring opportunity  (which I'm happy to take on) to use `setIgnore` in a few places within `GridItem`, I wasn't sure how you felt about those changes.

2022-09-18 19:22 UTC, zmanowar commented on src/main/java/thestonedturtle/bankedexperience/BankedCalculator.java
> +			final String name = i.getBankedItem().getItem().name();
There might be a better way to set the config so there's not duplicative code with the `SelectionListener`'s `ignored` [[L159](https://github.com/TheStonedTurtle/banked-experience/pull/91/files#diff-ebfbf21d3dc69377fb66335285fda23413649b6e838261fcd66329c9a4fb5b2dL159)]

2022-10-02 21:39 UTC, TheStonedTurtle commented
Instead of having buttons I think this would work better as being part of the right-click menu for the grid items:

```
Ignore/Include Item (this should depend on the current status of item)
Ignore All Items (always shown)
Include All Items (always shown)
```

2022-10-02 21:58 UTC, TheStonedTurtle requested changes

2022-10-02 21:58 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +	public void setIgnore(Boolean ignored) {
I'm not sure what you're talking about so you can add this as as separate commit and I can review it.

2022-10-02 21:58 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/BankedCalculator.java
> +			final String name = i.getBankedItem().getItem().name();
You'd have to do something like this so that the logic for ignoring an entry is the same regardless of where it's invoked: 
```java
	private void toggleIgnoreBankedItem(BankedItem item)
	{
		// Since this is a toggling if the set contains the item we want to include it, if it doesn't we want to ignore it
		boolean ignore = !ignoredItems.contains(item.getItem().name());
		ignoreBankedItem(item, ignore);
	}

	private void ignoreBankedItem(BankedItem item, boolean ignored)
	{
		// Save ignored status
		final String name = item.getItem().name();
		if (ignored)
		{
			ignoredItems.add(name);
		}
		else
		{
			ignoredItems.remove(name);
		}

		updateLinkedItems(item.getItem().getSelectedActivity());
	}

	private void setIgnoreAllItems(boolean ignored)
	{
		itemGrid.getPanelMap().values().forEach((i) ->
		{
			ignoreBankedItem(i.getBankedItem(), ignored);
			i.setIgnored(ignored);
		});
		// Update Config
		config.ignoredItems(Text.toCSV(ignoredItems));

		// Update UI
		calculateBankedXpTotal();
	}
```

and then update the SelectionListener's `ignore` method:
```java
toggleIgnoreBankedItem(item);

// Update Config
config.ignoredItems(Text.toCSV(ignoredItems));

// Update UI
calculateBankedXpTotal();

return true;
```

2022-10-05 17:07 UTC, zmanowar commented on src/main/java/thestonedturtle/bankedexperience/components/SelectionGrid.java
> +			final GridItem gridItem = new GridItem(item, img, qty, calc.getEnabledModifiers(), calc.getIgnoredItems().contains(item.getItem().name()), calc::setIgnoreAllItems);
Also working on getting the bulk actions config passed into `GridItem`.

2022-10-05 17:15 UTC, zmanowar commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +	GridItem(final BankedItem item, final AsyncBufferedImage icon, final int amount, final Collection<Modifier> modifiers, final boolean ignore, Consumer<Boolean> bulkIgnoreCallback, final boolean showB
Open to suggestions about calling a `BankedCalculator` method from within `GridItem`, Consumers were used for `BoostInput`.

Also passes in a single config value `config.showBulkActions` -- could pass in the entire config if necessary.

2022-10-05 20:26 UTC, TheStonedTurtle requested changes

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/BankedExperienceConfig.java
> +	@ConfigItem(
We dont need this behind a config option since it's now in the right-click menu

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/BankedCalculator.java
> +
remove empty spaces

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/BankedCalculator.java
> +
remove empty space, each function should have 1 blank line between them

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +
remove blank space

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +
Remove blank space

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> -			ignored = !ignored;
This needs to be flipped prior to calling the selectionListener as the `calculateBankedXpTotal` method checks the `ignored` value for grid items.

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> -				ignored = !ignored;
Because it's flipped prior to calling if it somehow fails it needs to be unflipped

2022-10-05 20:26 UTC, TheStonedTurtle commented on src/main/java/thestonedturtle/bankedexperience/components/GridItem.java
> +			setIgnore(!ignored);
Just call `setIgnore` with the flipped value if it was ignored successfully.

2022-11-24 08:52 UTC, merged